### ISSUE TITLE
v0/products/orders only returning 401 - Something went wrong, please try again later

### ISSUE THREAD

**Issue by asgeira** [vippsas/vipps-partner-api#18]
Currently testing out the partner API, but I'm only getting 401 when making a post request to/products/orders. I'm using the default request body (ACME Fantastic Fitness) from the Vipps Partner postman collection. accessToken/get, /salesunits and /merchants endpoints are all working fine with my partner credentials.

The response:
{"responseInfo":{"responseCode":401,"responseMessage":"Something went wrong, please try again later."},"result":{"message":"Something went wrong, please try again later."}}

When testing in a another enviroment  I also got "401 - APIM Unauthorized".

The steps I took:
- Downloaded postman collection and enviroment from https://github.com/vippsas/vipps-partner-api/blob/main/vipps-partner-postman.md
- Updated client_id, client_secret and Ocp-Apim-Subscription-Key to my partner keys
- Changed base_url to https://api.vipps.no, and orgno to 987654321 (example orgno from swagger docs)
- Sent a request without changing the Headers or Body

Is there something obvious I have missed, causing me to get this error?

**Comment by cloveras** [comment]
Hi

From the API Guide: https://github.com/vippsas/vipps-partner-api/blob/main/vipps-partner-api.md#submit-a-product-order-for-a-merchant

>>>Submit a product order for a merchant

Important: This endpoint is not yet available. This notice will be removed when it is.

[POST:/products/orders](https://vippsas.github.io/vipps-partner-api/#/Vipps%20Product%20Orders/order-product)

**Comment by cloveras** [comment]
I added the same info in the OpenAPI spec now: https://github.com/vippsas/vipps-partner-api/commit/eb894b49c01122e4afe0b2ca949d1a1a8bdffa23

**Comment by cloveras** [comment]
Aaaaand the Postman collection: https://github.com/vippsas/vipps-partner-api/commit/b4b4db1b4d892d225369d9b75bcb9ae0e54b249e

**Comment by cloveras** [comment]
We are really working to make  `[POST:/products/orders](https://vippsas.github.io/vipps-partner-api/#/Vipps%20Product%20Orders/order-product)` available! 

The final(?) tweaks to the API spec were merged earlier today: https://github.com/vippsas/vipps-partner-api/pull/17

**Comment by cloveras** [comment]
Closing this, as `POST:/products/orders` has been available for some time now.
