### ISSUE TITLE
Add info about changing base url to postmann collection 

### ISSUE THREAD

**Issue by kapir** [vippsas/vipps-partner-api#21]
Took some time to figure out by myself.

The initial Vipps environment is set up to be using https://apitest.vipps.no
But according to [vipps partner doc](https://github.com/vippsas/vipps-partner#how-to-check-if-a-merchant-is-signed-up-with-the-partner-as-partner) Partner keys do not work in the test environment. So this value should be changed.

Suggest mentioning it either in instructions or changing the importable environment, or adding instructions on how to use test environment

**Comment by rebeksburnett** [comment]
I've updated the documentation to hopefully make this more clear. Thanks!
