### ISSUE TITLE
Not able to order products for companies where the name contains æ/ø/å

### ISSUE THREAD

**Issue by EirikFinvold** [vippsas/vipps-partner-api#29]
It's perfectly legal to have æøå in company names, but in `v1/products/orders` you are validating the company name based on a different rule set.
Your response is:
`"{\"errors\":{\"salesUnitName\":[\"The field SalesUnitName must match the regular expression '^[a-zA-Z0-9- ]{1,30}$'.\"]},\"type\":\"https://httpstatuses.com/422\",\"title\":\"One or more validation errors occurred.\",\"status\":422,\"traceId\":\"00-8255303f173ae44a9ff7bc0cd7ec891f-d0af8f1595261aba-01\"}`"

[https://lovdata.no/lov/1985-06-21-79/§2-1](url)

**Comment by cloveras** [comment]
Thanks!

We'll fix this ASAP.

**Comment by niklud** [comment]
This is now fixed. Though I have to mention that salesUnitName is not the same as org name, and you are meant to have multiple per org.
